# Generated by Django 3.1 on 2021-04-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_auto_20210418_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
