# Generated by Django 3.1 on 2021-04-23 11:26

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210423_1712'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 23, 17, 26, 30, 730761)),
        ),
    ]
